theme = "mellow"

[editor]
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
